export default {
    id: "0000",
    name: "TEST Experiment 1: Acetaminophen",
    owner: "helium@ant-inc.co",
    experiments: [
        {
            id: "7c324003fad25",
            name: "Initialize",
            tasks: [
                {
                    id: "182b37724caf7",
                    note_id: 0,
                    note_name: "",
                    type: "chemical",
                    info: {
                        state: "solid",
                        amount: null,
                        c_unit: null,
                        p_unit: null,
                        v_unit: null,
                        volume: null,
                        w_unit: null,
                        weight: "2g",
                        display: "4-Aminophenol",
                        solvent: null,
                        sources: [],
                        nickname: null,
                        pressure: null,
                        property: [],
                        additional: "",
                        concentration: null,
                        product_number: null,
                    },
                },
                {
                    id: "87a583c7798d7",
                    note_id: 0,
                    note_name: "",
                    type: "chemical",
                    info: {
                        state: "liquid",
                        amount: null,
                        c_unit: null,
                        p_unit: null,
                        v_unit: null,
                        volume: "2.5mL",
                        w_unit: null,
                        weight: null,
                        display: "Acetic anhydride",
                        solvent: null,
                        sources: [],
                        nickname: null,
                        pressure: null,
                        property: [],
                        additional: "",
                        concentration: null,
                        product_number: null,
                    },
                },
                {
                    id: "c5c94f79bbfd9",
                    note_id: 0,
                    note_name: "",
                    type: "process",
                    info: {
                        name: "Add",
                        time: 0,
                        chem_to: { id: "87a583c7798d7", amount: "2.5mL" },
                        heating: false,
                        chem_for: { id: "182b37724caf7", amount: "2g" },
                        stirring: false,
                        gradually: false,
                    },
                },
                {
                    id: "a8efb3272fde2",
                    note_id: 0,
                    note_name: "",
                    type: "chemical",
                    info: {
                        state: "compound",
                        amount: null,
                        c_unit: null,
                        p_unit: null,
                        v_unit: null,
                        volume: null,
                        w_unit: null,
                        weight: null,
                        display: "4-Aminophenol + Acetic anhydride",
                        solvent: null,
                        sources: [
                            { id: "182b37724caf7", amount: "2g" },
                            { id: "87a583c7798d7", amount: "2.5mL" },
                        ],
                        nickname: null,
                        pressure: null,
                        property: ["added"],
                        additional: "",
                        concentration: null,
                        product_number: null,
                    },
                },
                {
                    id: "399994a97ebc9",
                    note_id: 0,
                    note_name: "",
                    type: "process",
                    info: {
                        rpm: "200",
                        name: "Stirring",
                        time: 0,
                        heating: false,
                        chem_for: { id: "a8efb3272fde2" },
                    },
                },
                {
                    id: "89f362310a1a1",
                    note_id: 0,
                    note_name: "",
                    type: "chemical",
                    info: {
                        state: "compound",
                        amount: null,
                        c_unit: null,
                        p_unit: null,
                        v_unit: null,
                        volume: null,
                        w_unit: null,
                        weight: null,
                        display: "4-Aminophenol + Acetic anhydride",
                        solvent: null,
                        sources: [
                            { id: "182b37724caf7", amount: "2g" },
                            { id: "87a583c7798d7", amount: "2.5mL" },
                        ],
                        nickname: null,
                        pressure: null,
                        property: ["added", "after stirring"],
                        additional: "",
                        concentration: null,
                        product_number: null,
                    },
                },
            ],
            comments: [
                {
                    id: "47ac91629aba9",
                    email: "hngskj@gmail.com",
                    date: 1603704934938,
                    content: "Hello \nHi",
                    resolved: true,
                    replies: [
                        {
                            id: "123123",
                            email: "helium@ant-inc.co",
                            date: 1603352508178,
                            content: "This is a reply",
                        },
                        {
                            id: "123123a",
                            email: "helium@ant-inc.com",
                            date: 1603487898178,
                            content: "This is a reply 2",
                        },
                    ],
                },
                {
                    id: "17ac91629aba7",
                    email: "helium@ant-inc.co",
                    date: 1603796020453,
                    content:
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.\nNullam vel urna lectus. Pellentesque faucibus ornare turpis, at rutrum tortor commodo vitae. \nDuis lobortis eros ut blandit lacinia.",
                    resolved: false,
                    replies: [
                        {
                            id: "asdffds",
                            email: "hello@ant-inc.co",
                            date: 1603312508178,
                            content: "Hello there",
                        },
                    ],
                },
            ],
        },
        {
            id: "9d6df25a0eb9a",
            name: "second",
            tasks: [
                {
                    id: "bd417553bfdea",
                    note_id: 0,
                    note_name: "",
                    type: "chemical",
                    info: {
                        state: "liquid",
                        amount: null,
                        c_unit: null,
                        p_unit: null,
                        v_unit: null,
                        volume: "6mL",
                        w_unit: null,
                        weight: null,
                        display: "water",
                        solvent: null,
                        sources: [],
                        nickname: null,
                        pressure: null,
                        property: [],
                        additional: "",
                        concentration: null,
                        product_number: null,
                    },
                },
                {
                    id: "3ae806358922",
                    note_id: 0,
                    note_name: "",
                    type: "process",
                    info: {
                        name: "Add",
                        time: 0,
                        chem_to: { id: "89f362310a1a1", amount: null },
                        heating: false,
                        chem_for: { id: "bd417553bfdea", amount: "6mL" },
                        stirring: false,
                        gradually: false,
                    },
                },
                {
                    id: "12a8e12a03a32",
                    note_id: 0,
                    note_name: "",
                    type: "chemical",
                    info: {
                        state: "compound",
                        amount: null,
                        c_unit: null,
                        p_unit: null,
                        v_unit: null,
                        volume: null,
                        w_unit: null,
                        weight: null,
                        display: "water + 4-Aminophenol + Acetic anhydride",
                        solvent: null,
                        sources: [
                            { id: "bd417553bfdea", amount: "6mL" },
                            { id: "89f362310a1a1", amount: null },
                        ],
                        nickname: null,
                        pressure: null,
                        property: ["added"],
                        additional: "",
                        concentration: null,
                        product_number: null,
                    },
                },
                {
                    id: "85f2a15b64a4c",
                    note_id: 0,
                    note_name: "",
                    type: "process",
                    info: {
                        name: "Water bath",
                        time: "20min",
                        chem_for: { id: "12a8e12a03a32" },
                        stirring: "on",
                        temperature: "60",
                    },
                },
                {
                    id: "24bc2367cc513",
                    note_id: 0,
                    note_name: "",
                    type: "chemical",
                    info: {
                        state: "compound",
                        amount: null,
                        c_unit: null,
                        p_unit: null,
                        v_unit: null,
                        volume: null,
                        w_unit: null,
                        weight: null,
                        display: "water + 4-Aminophenol + Acetic anhydride",
                        solvent: null,
                        sources: [
                            { id: "bd417553bfdea", amount: "6mL" },
                            { id: "89f362310a1a1", amount: null },
                        ],
                        nickname: null,
                        pressure: null,
                        property: ["added", "after heating on an water bath"],
                        additional: "",
                        concentration: null,
                        product_number: null,
                    },
                },
            ],
            comments: [],
        },
        {
            id: "fee408bf55b45",
            name: "3",
            tasks: [
                {
                    id: "0fe807ab6082c",
                    note_id: 0,
                    note_name: "",
                    type: "process",
                    info: {
                        name: "Cooling",
                        time: 0,
                        chem_for: { id: "24bc2367cc513" },
                        feeding_gas: null,
                        temperature: 0,
                    },
                },
                {
                    id: "db33c8547f7f8",
                    note_id: 0,
                    note_name: "",
                    type: "chemical",
                    info: {
                        state: "compound",
                        amount: null,
                        c_unit: null,
                        p_unit: null,
                        v_unit: null,
                        volume: null,
                        w_unit: null,
                        weight: null,
                        display: "water + 4-Aminophenol + Acetic anhydride",
                        solvent: null,
                        sources: [
                            { id: "bd417553bfdea", amount: "6mL" },
                            { id: "89f362310a1a1", amount: null },
                        ],
                        nickname: null,
                        pressure: null,
                        property: [
                            "added",
                            "after heating on an water bath",
                            "after cooling",
                        ],
                        additional: "",
                        concentration: null,
                        product_number: null,
                    },
                },
            ],
            comments: [],
        },
        {
            id: "51534b0b11dd5",
            name: "Finalize",
            tasks: [
                {
                    id: "d91920a6f3cdb",
                    note_id: 0,
                    note_name: "",
                    type: "process",
                    info: {
                        name: "Filtering",
                        feeding: "methanol",
                        chem_for: { id: "db33c8547f7f8" },
                    },
                },
                {
                    id: "b2516c7436879",
                    note_id: 0,
                    note_name: "",
                    type: "chemical",
                    info: {
                        state: "compound",
                        amount: "1.86g",
                        c_unit: null,
                        p_unit: null,
                        v_unit: null,
                        volume: null,
                        w_unit: null,
                        weight: null,
                        display: "water + 4-Aminophenol + Acetic anhydride",
                        solvent: null,
                        sources: [
                            { id: "bd417553bfdea", amount: "6mL" },
                            { id: "89f362310a1a1", amount: null },
                        ],
                        nickname: "Acetaminophen",
                        pressure: null,
                        property: [
                            "added",
                            "after heating on an water bath",
                            "after cooling",
                            "filtered",
                        ],
                        additional: "",
                        concentration: null,
                        product_number: null,
                    },
                },
            ],
            comments: [],
        },
    ],
};